### ISSUE TITLE
More pemissive license?

### ISSUE THREAD

**Issue by DarkEld3r** [kvark/copyless#16]
I'm not sure if it is appropriate, but can you please replace the license by a more permissive one? For example, MIT or Apache 2.0. I would like to use this library, but the company that I'm currently working at has a policy that forbids MPL license.

**Comment by kvark** [comment]
I'm totally open to switch to MIT+Apache, we have that in other projects too. Let's ask the contributors for permission:
- [x] @kvark
- [ ] @danielhenrymantilla
- [ ] @marcotoniut
- [ ] @eun-ice
- [ ] @erjanmx
- [ ] @badboy

If we don't get an answer in a week from now, we'll consider rewriting the relevant parts.

**Comment by badboy** [comment]
I merely fixed some typos.
But if required I hereby allow a a relicense to MIT/Apache

**Comment by eun-ice** [comment]
I contributed just a few lines to fix a bug. 

But I feel honored by being asked and of course I happily allow a relicense to MIT/Apache.

**Comment by danielhenrymantilla** [comment]
Fine for me :+1:

**Comment by kvark** [comment]
Alright, we are all set. Thanks everyone for responding!
@DarkEld3r would you be interested in making a PR that switches us to dual-license?
