### ISSUE TITLE
Why is this crate deprecated?

### ISSUE THREAD

**Issue by wmanley** [kvark/copyless#25]
I see in the crate description that this crate is deprecated.  Please consider adding a note to the README describing/linking to a description of why. Is it just unmaintained, or is it no longer necessary thanks to improvements to the Rust standard library, or maybe something else?

**Comment by kvark** [comment]
Thank you for filing! It's basically #22
Added a small note to README in dc36153ddc53c47f721d4415edc0d14fb6b40f36
